name: BSpawn
version: 1.1
description: Player spawn command
author: RedstoneFiend
website: https://github.com/RedstoneFiend/BSpawn

main: io.github.redstonefiend.bspawn.Main
database: false

commands:
    bspawn:
        description: Reload Boomerand Spawn configuration.
        usage: /<command> [ver[sion] | reload]
        permission: bspawn.bspawn
        permission-message: You don't have <permission>
    setspawn:
        description: Set server spawn for new players. Optionally force all joining players to spawn.
        usage: /<command> [force]
        permission: bspawn.setspawn
        permission-message: You don't have <permission>
    unsetspawn:
        description: Unset server spawn for new players. Spawn will follow default Minecraft rules.
        usage: /<command>
        permission: bspawn.unsetspawn
        permission-message: You don't have <permission>
    spawn:
        description: Teleport to spawn.
        usage: /<command>
    spawn reload:
        description: Reloads BSpawn configuration.
        usage: /<command>
        permission: bspawn.reload
        permission-message: You don't have <permission>

# Permissions
permissions:
    bspawn.*:
        description: Gives access to all BSpawn commands
        children:
            bspawn.bspawn: true
            bspawn.setspawn: true
            bspawn.spawnother: true
            bspawn.unsetspawn: true
            bspawn.reload: true
    bspawn.bspawn:
        description: Allows you to access administrative commands.
        default: op
    bspawn.spawnother:
        description: Allows you to teleport other players to spawn.
        default: op
    bspawn.setspawn:
        description: Allows you to set server spawn location.
        default: op
    bspawn.unsetspawn:
        description: Allows you to unset server spawn location.
        default: op
    bspawn.reload:
        description: Allows you to reload config.yml.
        default: op
